#Win Prediction of team by 2nd Inning performance

##Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##Importing Data and Data study 

In [2]:
dataset = pd.read_csv('./data/odi_2nd_inning.csv')

In [3]:
dataset.head()

mid        date                                   venue bat_team  \
0  1524  11-01-2013  Saurashtra Cricket Association Stadium    India   
1  1524  11-01-2013  Saurashtra Cricket Association Stadium    India   
2  1524  11-01-2013  Saurashtra Cricket Association Stadium    India   
3  1524  11-01-2013  Saurashtra Cricket Association Stadium    India   
4  1524  11-01-2013  Saurashtra Cricket Association Stadium    India   

  bowl_team    batsman   bowler  runs  wickets  overs  runs_last_5  \
0   England  AM Rahane  ST Finn     0        0    0.1            0   
1   England  AM Rahane  ST Finn     0        0    0.2            0   
2   England  AM Rahane  ST Finn     0        0    0.3            0   
3   England  AM Rahane  ST Finn     4        0    0.4            4   
4   England  AM Rahane  ST Finn     4        0    0.5            4   

   wickets_last_5  striker  non_striker  total  win  
0               0        0            0    325    0  
1               0        0            0    325    0  
2               0        0            0    325    0  
3               0        4            0    325    0  
4               0        4            0    325    0

In [4]:
print(len(dataset["bat_team"].unique()))
print(len(dataset["bowl_team"].unique()))
print(len(dataset["batsman"].unique()))
print(len(dataset["bowler"].unique()))

19
19
558
418


In [5]:
dataset.describe()

mid           runs        wickets          overs  \
count  128211.000000  128211.000000  128211.000000  128211.000000   
mean     2526.773046     108.289928       2.953366      21.787245   
std       638.340489      71.850698       2.383497      13.259318   
min      1524.000000       0.000000       0.000000       0.100000   
25%      1958.000000      49.000000       1.000000      10.400000   
50%      2397.000000     100.000000       2.000000      21.200000   
75%      3119.000000     159.000000       4.000000      32.500000   
max      3880.000000     372.000000      10.000000      49.800000   

         runs_last_5  wickets_last_5        striker    non_striker  \
count  128211.000000   128211.000000  128211.000000  128211.000000   
mean       23.710563        0.700548      32.813674      11.765730   
std        10.129097        0.851432      26.491717      14.834441   
min         0.000000        0.000000       0.000000       0.000000   
25%        17.000000        0.000000      12.000000       1.000000   
50%        23.000000        0.000000      27.000000       6.000000   
75%        30.000000        1.000000      47.000000      17.000000   
max        81.000000        6.000000     180.000000     117.000000   

               total            win  
count  128211.000000  128211.000000  
mean      267.213523       0.477533  
std        60.260179       0.499497  
min        67.000000       0.000000  
25%       229.000000       0.000000  
50%       268.000000       0.000000  
75%       307.000000       1.000000  
max       444.000000       1.000000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128211 entries, 0 to 128210
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   mid             128211 non-null  int64  
 1   date            128211 non-null  object 
 2   venue           128211 non-null  object 
 3   bat_team        128211 non-null  object 
 4   bowl_team       128211 non-null  object 
 5   batsman         128211 non-null  object 
 6   bowler          128211 non-null  object 
 7   runs            128211 non-null  int64  
 8   wickets         128211 non-null  int64  
 9   overs           128211 non-null  float64
 10  runs_last_5     128211 non-null  int64  
 11  wickets_last_5  128211 non-null  int64  
 12  striker         128211 non-null  int64  
 13  non_striker     128211 non-null  int64  
 14  total           128211 non-null  int64  
 15  win             128211 non-null  int64  
dtypes: float64(1), int64(9), object(6)
memory usage: 15.7+ M

In [7]:
dataset.corr()

mid      runs   wickets     overs  runs_last_5  \
mid             1.000000  0.027904 -0.022598 -0.007459     0.029244   
runs            0.027904  1.000000  0.651917  0.941468     0.530775   
wickets        -0.022598  0.651917  1.000000  0.762226     0.153108   
overs          -0.007459  0.941468  0.762226  1.000000     0.397507   
runs_last_5     0.029244  0.530775  0.153108  0.397507     1.000000   
wickets_last_5 -0.011049  0.191694  0.509808  0.219448    -0.064110   
striker         0.002806  0.570331  0.057577  0.488978     0.522058   
non_striker    -0.003187  0.269376 -0.182686  0.203322     0.416294   
total           0.009431  0.205284  0.136508  0.105727     0.172561   
win            -0.030045  0.028519 -0.274415 -0.021632     0.089527   

                wickets_last_5   striker  non_striker     total       win  
mid                  -0.011049  0.002806    -0.003187  0.009431 -0.030045  
runs                  0.191694  0.570331     0.269376  0.205284  0.028519  
wickets               0.509808  0.057577    -0.182686  0.136508 -0.274415  
overs                 0.219448  0.488978     0.203322  0.105727 -0.021632  
runs_last_5          -0.064110  0.522058     0.416294  0.172561  0.089527  
wickets_last_5        1.000000 -0.233254    -0.458034  0.090513 -0.227709  
striker              -0.233254  1.000000     0.553141  0.076455  0.207660  
non_striker          -0.458034  0.553141     1.000000  0.013766  0.236693  
total                 0.090513  0.076455     0.013766  1.000000 -0.505343  
win                  -0.227709  0.207660     0.236693 -0.505343  1.000000

In [8]:
dataset.columns

Index(['mid', 'date', 'venue', 'bat_team', 'bowl_team', 'batsman', 'bowler',
       'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5', 'striker',
       'non_striker', 'total', 'win'],
      dtype='object')

In [9]:
K = dataset.iloc[:, [3,4,5,6,7,8,9,12,13,14,15]].values

In [10]:
K

array([['India', 'England', 'AM Rahane', ..., 0, 325, 0],
       ['India', 'England', 'AM Rahane', ..., 0, 325, 0],
       ['India', 'England', 'AM Rahane', ..., 0, 325, 0],
       ...,
       ['England', 'Ireland', '2', ..., 0, 198, 1],
       ['England', 'Ireland', '1', ..., 0, 198, 1],
       ['England', 'Ireland', '4', ..., 0, 198, 1]], dtype=object)

###Label Encoding Name of player and Playing teams

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
K[:, 0] = le.fit_transform(K[:, 0])
K[:, 1] = le.fit_transform(K[:, 1])
K[:, 2] = le.fit_transform(K[:, 2])
K[:, 3] = le.fit_transform(K[:, 3])

In [12]:
# data = dataset.iloc[:, [3,4,5,6,7,8,9,12,13,14,15]]
column_names = ['bat_team', 'bowl_team', 'batsman', 'bowler', 'runs', 'wickets',
       'overs', 'striker', 'non_striker', 'total', 'win']
df = pd.DataFrame(data = K,
                 columns = column_names)

In [13]:
print(len(df["bat_team"].unique()))
print(len(df["bowl_team"].unique()))
print(len(df["batsman"].unique()))
print(len(df["bowler"].unique()))

19
19
558
418


In [14]:
df["bat_team"] = df.bat_team.astype(int)
df["bowl_team"] = df.bowl_team.astype(int)
df["batsman"] = df.batsman.astype(int)
df["bowler"] = df.bowler.astype(int)
df["runs"] = df.runs.astype(int)
df["wickets"] = df.wickets.astype(int)
df["overs"] = df.overs.astype(int)
df["striker"] = df.striker.astype(int)
df["non_striker"] = df.non_striker.astype(int)
df["total"] = df.total.astype(int)
df["win"] = df.win.astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128211 entries, 0 to 128210
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   bat_team     128211 non-null  int32
 1   bowl_team    128211 non-null  int32
 2   batsman      128211 non-null  int32
 3   bowler       128211 non-null  int32
 4   runs         128211 non-null  int32
 5   wickets      128211 non-null  int32
 6   overs        128211 non-null  int32
 7   striker      128211 non-null  int32
 8   non_striker  128211 non-null  int32
 9   total        128211 non-null  int32
 10  win          128211 non-null  int32
dtypes: int32(11)
memory usage: 5.4 MB


In [16]:
df.head()

bat_team  bowl_team  batsman  bowler  runs  wickets  overs  striker  \
0         6          4       30     353     0        0      0        0   
1         6          4       30     353     0        0      0        0   
2         6          4       30     353     0        0      0        0   
3         6          4       30     353     4        0      0        4   
4         6          4       30     353     4        0      0        4   

   non_striker  total  win  
0            0    325    0  
1            0    325    0  
2            0    325    0  
3            0    325    0  
4            0    325    0

In [17]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [18]:
X

array([[  6,   4,  30, ...,   0,   0, 325],
       [  6,   4,  30, ...,   0,   0, 325],
       [  6,   4,  30, ...,   0,   0, 325],
       ...,
       [  4,   7,   2, ...,  26,   0, 198],
       [  4,   7,   1, ...,  71,   0, 198],
       [  4,   7,   4, ...,  76,   0, 198]])

In [19]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [20]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(df, df['bat_team']):
  strat_train_set = df.loc[train_index]
  strat_test_set = df.loc[test_index]
print("For training set: ")
print(strat_train_set['bat_team'].value_counts())
print("For testing set: ")
print(strat_test_set['bat_team'].value_counts())
X_train = strat_train_set.iloc[:,:-1].values
y_train = strat_train_set.iloc[:,-1].values
X_test = strat_test_set.iloc[:,:-1].values
y_test = strat_test_set.iloc[:,-1].values

For training set: 
6     11838
11     9905
15     9678
18     9318
4      9168
14     8655
1      8523
17     8519
10     7766
7      4903
2      4588
0      3881
16     2447
13     1303
5       687
8       412
9       412
12      362
3       203
Name: bat_team, dtype: int64
For testing set: 
6     2960
11    2476
15    2420
18    2329
4     2292
14    2164
1     2131
17    2130
10    1941
7     1226
2     1147
0      970
16     612
13     326
5      172
9      103
8      103
12      90
3       51
Name: bat_team, dtype: int64


In [21]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

##Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
type(X_train)
X_train[:, 0]=X_train[:, 0].astype('int')
type(X_train[:, 0])

numpy.ndarray

##Training the model 

In [24]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'linear', random_state = 0)
# classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

##Calculating Accuracy by Confusion matrix

In [25]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12433   697]
 [  919 11594]]


0.9369808524743595

##Comparing predicted value and Actual value

In [26]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 1]
 [1 1]
 [1 1]]
